### ISSUE TITLE
Problema d'Installazione

### ISSUE THREAD

**Issue by enzococca** [jbogdani/BraDypUS#1]
Salve,
Ho provato ad installare Bradypus su un sistema win 10 con php 7.4. Al momento della creazione di un progetto mi dava  un errore sul db sia sqlite che postgres.
In allegato il file error.log.
Ho provato ad avviare anche con credenziali di Amministratore ma il risultato è lo stesso.
Come posso risolvere questo problema?
Grazie
E

[error.log](https://github.com/bdus-db/BraDypUS/files/5803886/error.log)

**Comment by enzococca** [comment]
Ok risolto installando XAMP.

Grazie

**Comment by jbogdani** [comment]
Hello,
It is a php installation issue. Here is your log: 
```
[2021-01-12T12:46:47.177208+01:00] bdus.ERROR: DB\DBException: PDOException: could not find driver in C:\BraDypUS\lib\DB\DB.php:338 Stack trace: #0 C:\BraDypUS\lib\DB\DB.php(338): PDO->__construct('sqlite:projects...', '', '', Array) #1 C:\BraDypUS\lib\DB\DB.php(63): DB\DB->initializePDO('sqlite', 'sqlite:projects...', '', '') #2 C:\BraDypUS\lib\DB\System\CreateApp.php(51): DB\DB->__construct('test', Array) #3 C:\BraDypUS\modules\new_app\new_app.php(36): DB\System\CreateApp->__construct('test', 'prova inserimen...', 'enzo.ccc@gmail....', 'baselice', 'sqlite', '', '', '', '', '') #4 C:\BraDypUS\lib\Bdus\App.php(215): new_app_ctrl->add_app() #5 C:\BraDypUS\lib\Bdus\App.php(71): Bdus\App->route() #6 C:\BraDypUS\index.php(40): Bdus\App->start() #7 {main} in C:\BraDypUS\lib\DB\DB.php:348 Stack trace: #0 C:\BraDypUS\lib\DB\DB.php(63): DB\DB->initializePDO('sqlite', 'sqlite:projects...', '', '') #1 C:\BraDypUS\lib\DB\System\CreateApp.php(51): DB\DB->__construct('test', Array) #2 C:\BraDypUS\modules\new_app\new_app.php(36): DB\System\CreateApp->__construct('test', 'prova inserimen...', 'enzo.ccc@gmail....', 'baselice', 'sqlite', '', '', '', '', '') #3 C:\BraDypUS\lib\Bdus\App.php(215): new_app_ctrl->add_app() #4 C:\BraDypUS\lib\Bdus\App.php(71): Bdus\App->route() #5 C:\BraDypUS\index.php(40): Bdus\App->start() #6 {main} [] []
```

This is because your php installation does not include either `php_pdo`, `pdo_sqlite` or `pdo_pdo_pgsql` which [are required](https://docs.bdus.cloud/environment/system-requirements).

You can use `phpinfo()` function to check your installation or `php -i` from the command line and check for `PDO support` and `PDO drivers` in the output.

A fast terminal-based way for doing this (sorry only on *nix systems) is the following :

```bash
% php -i | grep "PDO support"
PDO support => enabled
```
and 
```bash
% php -i | grep "PDO drivers"
PDO drivers => dblib, mysql, odbc, pgsql, sqlite
```
The browser way is opening in the browser a php script containing the folloing code
```php
<?php
phpinfo();
```
and looking for this section:
![image](https://user-images.githubusercontent.com/1449293/104367345-f7cf4a00-551a-11eb-97eb-d19adcc317a6.png)

XAMPP fixed the issue because  XAMPP is shipped with most common extensions already enabled.

I hope this helps,
cheers
